FROM golang:1.21

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download
RUN go mod tidy

COPY ./ ./

EXPOSE 8000

RUN go build -o /shakku-websocket-chat

# 起動コマンド
CMD ["/shakku-websocket-chat"]
